### ISSUE TITLE
Atom feed?

### ISSUE THREAD

**Issue by tonyg** [joearms/joearms.github.com#2]
Any chance of an Atom (or RSS) feed for the blog, Joe? It'll be useful at the very least until Google Reader gets shut down in a few weeks ;-)

**Comment by jeremy-w** [comment]
Please consider reopening and then resolving this issue. The feed has dried up with the move away from Jekyll.

This issue was fixed by Jekyll, but has been reintroduced by the move to [new blogging software](https://joearms.github.io/2016/05/31/New-blogging_software.html). It looks like GitHub is still serving the raw Jekyll template for the feed at https://joearms.github.io/feed.xml. (Thanks, GitHub.)

**Comment by joearms** [comment]
I think I've fixed it. I'd forgotten to create a feed.xml file - Hope it's ok now

**Comment by jeremy-w** [comment]
It's working great now, thanks!
